swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>
    <div class="form-container">
  <h1><font Color=red>Visit Our New WebSite </h1><h3><mark><a href="https://example.com">e x a m p l e . c o m </a></mark></h3><br><br><br>
  "/><img src="x"><a href="https://evil.com">login</a>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
